### PR TITLE
Add nice badges

### PR DESCRIPTION
**Pull request by szepeviktor**
As this add-on gains popularity ....

kép

Looks great!

### CODE REVIEW

**Comment by szepeviktor** [comment]
Maybe you could add

[PHPStan](https://phpstan.org/)

```markdown
[![PHPStan](https://img.shields.io/badge/PHPStan-enabled-31C653)](https://phpstan.org/)
```

**Comment by szepeviktor** [comment]
@NielsdeBlaauw What do you think?

**Comment by NielsdeBlaauw** [comment]
Great. Let's add these!

**Review by NielsdeBlaauw — APPROVED** [review]

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
