### PR TITLE
Let' see PHPStan in action!

### PR DESCRIPTION
**Pull request by szepeviktor**
w/o cs2pr

### CODE REVIEW

**Comment by szepeviktor** [comment]
@NielsdeBlaauw 

# 🤯 

Shocky-shock.

kép

**Comment by NielsdeBlaauw** [comment]
That's pretty cool! I didn't know phpstan does this by itself. Someone should update the [php-setup documentation ](https://github.com/shivammathur/setup-php#other-tools).

**Comment by szepeviktor** [comment]
Done.

https://github.com/shivammathur/setup-php/pull/292

**Comment by NielsdeBlaauw** [comment]
Removed in 9fce90bc1812064627e208b24a2eee1ae37a3e79

**Pull request closed without merging**
